# Generated by Django 6.0.3 on 2026-03-16 10:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mode', models.CharField(choices=[('Text', 'Text'), ('Voice', 'Voice'), ('Call', 'Call')], max_length=10)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='DISPATCHED', max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Trial', 'Trial'), ('Basic', 'Basic'), ('Advance', 'Advance'), ('Pro', 'Pro')], default='Trial', max_length=20)),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('text_used', models.IntegerField(default=0)),
                ('call_used', models.IntegerField(default=0)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.business')),
            ],
        ),
    ]
